apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  type: {{ .Values.frontend.service.type | default "ClusterIP" }}
  selector:
    app: {{ .Chart.Name }}
  ports:
    - port: {{ .Values.frontend.service.port | default 80 }}
      targetPort: {{ .Values.frontend.containerPort | default 80 }}
